# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "shailendra-app"
client_id = "f6f421a4a5e893bb324b63f7d96719cf"
application_url = "https://volunteers-sussex-mixing-ownership.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://volunteers-sussex-mixing-ownership.trycloudflare.com/auth/callback",
  "https://volunteers-sussex-mixing-ownership.trycloudflare.com/auth/shopify/callback",
  "https://volunteers-sussex-mixing-ownership.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
