# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "shailendra-app"
client_id = "f6f421a4a5e893bb324b63f7d96719cf"
application_url = "https://american-certification-rrp-hundreds.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://american-certification-rrp-hundreds.trycloudflare.com/auth/callback",
  "https://american-certification-rrp-hundreds.trycloudflare.com/auth/shopify/callback",
  "https://american-certification-rrp-hundreds.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shailendra-development-store-meroxio.myshopify.com"
