# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "MeroxIO Sticky Mobile Menu Bar"
client_id = "ae4d222b190280dbc5394b060e41254d"
application_url = "https://mobilemenu.meroxioapps.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://mobilemenu.meroxioapps.com/auth/callback",
  "https://mobilemenu.meroxioapps.com/auth/shopify/callback",
  "https://mobilemenu.meroxioapps.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://mobilemenu.meroxioapps.com/api/webhooks"
  customer_data_request_url = "https://mobilemenu.meroxioapps.com/api/webhooks"
  shop_deletion_url = "https://mobilemenu.meroxioapps.com/api/webhooks"

[pos]
embedded = false
