# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Staging"
client_id = "bfb95502aa8f4f718b14d09136fef838"
application_url = "https://adam-expenditures-hawaii-nsw.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://adam-expenditures-hawaii-nsw.trycloudflare.com/auth/callback",
  "https://adam-expenditures-hawaii-nsw.trycloudflare.com/auth/shopify/callback",
  "https://adam-expenditures-hawaii-nsw.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2022-10"

[app_proxy]
url = "https://adam-expenditures-hawaii-nsw.trycloudflare.com/api/atc-clicked"
subpath = "atc-clicked"
prefix = "apps"

[pos]
embedded = false

[build]
dev_store_url = "shivam-development-store.myshopify.com"
automatically_update_urls_on_dev = true
