# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Staging"
client_id = "bfb95502aa8f4f718b14d09136fef838"
application_url = "https://success-navigate-received-announcements.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://success-navigate-received-announcements.trycloudflare.com/auth/callback",
  "https://success-navigate-received-announcements.trycloudflare.com/auth/shopify/callback",
  "https://success-navigate-received-announcements.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2022-10"

[app_proxy]
url = "https://success-navigate-received-announcements.trycloudflare.com//app/createBundle"
subpath = "createBundle"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shailendra-development-store-meroxio.myshopify.com"
