# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "753e1004b9f1e261b63f2d6636dac445"
application_url = "https://gallery-scoop-let-dust.trycloudflare.com"
embedded = true
name = "ankit-app-dev"
handle = "ankit-app-dev"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "meroxiodev2.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://gallery-scoop-let-dust.trycloudflare.com/auth/callback",
  "https://gallery-scoop-let-dust.trycloudflare.com/auth/shopify/callback",
  "https://gallery-scoop-let-dust.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://gallery-scoop-let-dust.trycloudflare.com/api/meroxio-proxy"
subpath = "meroxio-proxy"
prefix = "apps"

[pos]
embedded = false
