# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ab43e0f6dbc44a0e3e7b138757b76021"
application_url = "https://app3.meroxioapps.com/"
embedded = true
name = "Move To Wishlist"
handle = "move-to-wishlist-1"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[auth]
redirect_urls = [
  "https://app3.meroxioapps.com/auth/callback",
  "https://app3.meroxioapps.com/auth/shopify/callback",
  "https://app3.meroxioapps.com/api/auth/callback"
]

[app_proxy]
url = "https://app3.meroxioapps.com/api/meroxio-proxy"
subpath = "meroxio-proxy"
prefix = "apps"

[pos]
embedded = false

[build]
include_config_on_deploy = true
