# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "866588ebf1c791f58652afae4e8cb9f2"
name = "Scroll Up Pro"
application_url = "https://scrollup.solnix.store"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://scrollup.solnix.store/auth/callback",
  "https://scrollup.solnix.store/auth/shopify/callback",
  "https://scrollup.solnix.store/api/auth/callback"
]

[app_proxy]
url = "https://scrollup.solnix.store/api/scroll-to-top"
subpath = "scroll-to-top"
prefix = "apps"
