# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "shailendra-dev-app"
client_id = "86d68bcdf4dca4e2529f036a18a101e4"
application_url = "https://accepted-destruction-commit-army.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://accepted-destruction-commit-army.trycloudflare.com/auth/callback",
  "https://accepted-destruction-commit-army.trycloudflare.com/auth/shopify/callback",
  "https://accepted-destruction-commit-army.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2022-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shailendra-development-store-meroxio.myshopify.com"
